[package]
name = "cctp_primitives"
version = "0.1.0"
authors = [""]
edition = "2018"

[dependencies]
algebra = {version = "0.1.0", git = "https://github.com/HorizenOfficial/ginger-lib.git", branch = "algebra_ocl", features = ["tweedle"]}
primitives = {version = "0.1.0", git = "https://github.com/HorizenOfficial/ginger-lib.git", branch = "algebra_ocl", features = ["smt", "mnt4_753", "mnt6_753", "tweedle"]}
#algebra = { path = "../../ginger-lib/algebra" }
#primitives = { path = "../../ginger-lib/primitives", features = ["smt"] }
rand = { version = "0.8.3" }
sha1 = "0.6.0"

bit-vec = "0.6"
bzip2 = "0.4.2"
flate2 = "1.0.20"


