[package]
name = "cctp_primitives"
version = "0.1.0"
authors = [""]
edition = "2018"

[dependencies]
algebra = {version = "0.1.0", git = "https://github.com/HorizenOfficial/ginger-lib.git", branch = "algebra_ocl"}
primitives = {version = "0.1.0", features = ["smt", "tweedle"], git = "https://github.com/HorizenOfficial/ginger-lib.git", branch = "algebra_ocl"}
poly-commit = { git = "https://github.com/HorizenLabs/poly-commit", branch = "dev_pub_generators" }
#algebra = { path = "../../ginger-lib/algebra" }
#primitives = { path = "../../ginger-lib/primitives", features = ["smt", "tweedle"] }
rand = { version = "0.7" }
byteorder = "1.4.2"
digest = "0.8"
rayon = { version = "1" }
blake2 = { version = "0.8", default-features = false }

bit-vec = "0.6"
bzip2 = "0.4.2"
flate2 = "1.0.20"


