[package]
name = "cctp_primitives"
version = "0.1.0"
authors = [""]
edition = "2018"

[dependencies]
algebra = { git = "https://github.com/HorizenOfficial/ginger-lib", branch = "audit_fixes_005", features = ["parallel", "tweedle", "derive"] }
bench-utils = { git = "https://github.com/HorizenOfficial/ginger-lib.git", branch = "audit_fixes_005" }
primitives = { git = "https://github.com/HorizenOfficial/ginger-lib.git", branch = "audit_fixes_005", features = ["merkle_tree", "tweedle"]}
proof-systems = { git = "https://github.com/HorizenOfficial/ginger-lib.git", branch = "audit_fixes_005", features = ["darlin"]}
r1cs-core = { git = "https://github.com/HorizenOfficial/ginger-lib.git", branch = "audit_fixes_005" }

marlin = { git = "https://github.com/HorizenLabs/marlin", branch = "audit_fixes_005" }
poly-commit = { git = "https://github.com/HorizenLabs/poly-commit", branch = "audit_fixes_005" }

rand = { version = "0.8.4" }
byteorder = "1.4.2"
lazy_static = "1.4.0"
blake2 = { version = "0.8.1", default-features = false }
sha1 = "0.6.0"
bit-vec = "0.6"
bzip2 = "0.4.2"
flate2 = "1.0.20"

[dev-dependencies]
serial_test = "*"

[features]
asm = ["marlin/asm", "poly-commit/asm", "algebra/llvm_asm"]
