[package]
name = "cctp_primitives"
version = "0.1.0"
authors = [
    "Alberto Benegiamo",
    "Daniele Di Benedetto <daniele@horizenlabs.io>",
    "Paolo Tagliaferri <paolotagliaferri@horizenlabs.io>",
    "Andrii Nastenko <andrii.nastenko@iohk.io>",
    "Oleksandr Iozhytsia <oleksandr@zensystem.io>",
    "Maksym Vereshchak <phoinic@gmail.com>",
    "Alberto Sala <alsala@zensystem.io>",
    "Luigi Varriale <luigi@horizenlabs.io>",
    "cronicc <cronic@horizenlabs.io>",
]
edition = "2018"

[dependencies]
algebra = { git = "https://github.com/HorizenOfficial/ginger-lib", branch = "release_0_3_0", features = ["parallel", "tweedle", "derive"] }
primitives = { git = "https://github.com/HorizenOfficial/ginger-lib.git", branch = "release_0_3_0", features = ["merkle_tree", "tweedle"]}
proof-systems = { git = "https://github.com/HorizenOfficial/ginger-lib.git", branch = "release_0_3_0", features = ["darlin"]}

marlin = { git = "https://github.com/HorizenLabs/marlin", branch = "release_0_2_0" }
poly-commit = { git = "https://github.com/HorizenLabs/poly-commit", branch = "release_0_2_0" }

rand = { version = "0.8.4" }
byteorder = "1.4.2"
lazy_static = "1.4.0"
blake2 = { version = "0.8.1", default-features = false }
sha1 = "0.6.0"
bit-vec = "0.6"
bzip2 = "0.4.2"
flate2 = "1.0.20"

[dev-dependencies]
serial_test = "*"

[features]
asm = ["marlin/asm", "poly-commit/asm", "algebra/llvm_asm"]
