[package]
name = "cctp_primitives"
version = "0.1.0"
authors = [""]
edition = "2018"

[dependencies]
algebra = {version = "0.1.0", git = "https://github.com/HorizenOfficial/ginger-lib.git", branch = "development_tmp"}
primitives = {version = "0.1.0", features = ["merkle_tree", "tweedle"], git = "https://github.com/HorizenOfficial/ginger-lib.git", branch = "development_tmp"}

byteorder = "1.4.2"
rand = { version = "0.7" }
sha1 = "0.6.0"
bit-vec = "0.6"
bzip2 = "0.4.2"
flate2 = "1.0.20"
