[package]
name = "cctp_primitives"
version = "0.1.0"
authors = [""]
edition = "2018"

[dependencies]
algebra = {version = "0.1.0", git = "https://github.com/HorizenOfficial/ginger-lib.git", branch = "algebra_ocl"}
primitives = {version = "0.1.0", features = ["smt", "mnt4_753", "mnt6_753"], git = "https://github.com/HorizenOfficial/ginger-lib.git", branch = "algebra_ocl"}
#algebra = { path = "../../ginger-lib/algebra" }
#primitives = { path = "../../ginger-lib/primitives", features = ["smt"] }
rand = { version = "0.7" }
byteorder = "1.4.2"

[lib]
name = "zendoo_cctp"
path = "src/lib.rs"
crate_type = ["cdylib"]
